# Default Helm values for the Jellyfin chart. These can be overridden in
# group_vars or host_vars.
jellyfin_helm_values:
  service:
    type: LoadBalancer
    loadBalancerIP: "{{ jellyfin_lb_ip }}"
    port: 8096
    annotations:
      metallb.universe.tf/allow-shared-ip: jellyfin-media

  persistence:
    config:
      # This is where Jellyfin stores its configuration and metadata, including
      # user data, watch history, and library information.
      enabled: true
      storageClass: nfs-jellyfin-config
      accessMode: ReadWriteOnce
      size: 5Gi
    media:
      # We will define multiple custom volumes for different media types. This
      # provides better organization and allows independent management.
      enabled: false
    transcode:
      # We don't need to persist transcodes across pod restarts and writing to
      # NFS can be slow.
      enabled: true
      type: emptyDir

  # Custom mounts for our media libraries. We use our own PVCs for media,
  # decoupling the media library from Jellyfin.
  # TODO: Make this configurable via group_vars or host_vars.
  volumes:
    - name: media-movies
      persistentVolumeClaim:
        claimName: jellyfin-movies-pvc
    - name: media-tv
      persistentVolumeClaim:
        claimName: jellyfin-tv-pvc

  volumeMounts:
    - name: media-movies
      mountPath: /media/movies
    - name: media-tv
      mountPath: /media/tv

  podSecurityContext:
    fsGroup: 65534

  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 4Gi
