- name: Make sure the media namespace exists
  kubernetes.core.k8s:
    name: media
    api_version: v1
    kind: Namespace
    state: present

- name: Create Persistent Volume Claims
  kubernetes.core.k8s:
    apply: true
    state: present
    src: pvcs.yaml

- name: Create service endpoints for Jellyfin
  kubernetes.core.k8s:
    apply: true
    state: present
    definition: "{{ lookup('template', 'service.yaml.j2') | from_yaml }}"

- name: Deploy Jellyfin via manifest
  kubernetes.core.k8s:
    apply: true
    state: present
    definition: "{{ lookup('template', 'deployment.yaml.j2') | from_yaml }}"
