apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-movies-pvc
  namespace: media
spec:
  storageClassName: nfs-jellyfin-media
  # ReadWriteMany allows this volume to be mounted by other pods (e.g. Radarr,
  # Sonarr) simultaneously.
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # TODO: Make this configurable via group_vars or host_vars.
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-tv-pvc
  namespace: media
spec:
  storageClassName: nfs-jellyfin-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # TODO: Make this configurable via group_vars or host_vars.
      storage: 50Gi
